export const skills = [
    {
        key: 0,
        image: '/skills/python.png',
        alt: 'Python',
        title: 'Python',
        color: 'shadow-yellow-200',
    },
    {
        key: 1,
        image: '/skills/javascript.png',
        alt: 'JavaScript',
        title: 'JavaScript',
        color: 'shadow-yellow-300',
    },
    {
        key: 2,
        image: '/skills/react.png',
        alt: 'React',
        title: 'React',
        color: 'shadow-blue-300',
    },
    {
        key: 3,
        image: '/skills/tailwind.png',
        alt: 'Tailwind CSS',
        title: 'Tailwind CSS',
        color: 'shadow-cyan-300',
    },
    {
        key: 4,
        image: '/skills/nextjs.png',
        alt: 'Next.js',
        title: 'Next.js',
        color: 'shadow-black-300',
    },
    {
        key: 5,
        image: '/skills/nodejs.png',
        alt: 'Node.js',
        title: 'Node.js',
        color: 'shadow-green-300',
    },
    {
        key: 6,
        image: '/skills/c-sharp.png',
        alt: 'C#',
        title: 'C#',
        color: 'shadow-purple-600',
    },
    {
        key: 7,
        image: '/skills/java.png',
        alt: 'Java',
        title: 'Java',
        color: 'shadow-slate-600',
    },
];